[package]
name = "cargo-nx"
version = "0.2.0"
authors = ["XorTroll", "LNSD"]
license = "MIT"
homepage = "https://github.com/nx-std/"
repository = "https://github.com/nx-std/tools/"
edition = "2024"
description = "Cargo subcommand to simplify creating and building Nintendo Switch homebrew projects"

[features]
## JSON Schema generation for the NPDM descriptor types
json-schema = ["dep:schemars"]

[dependencies]
aes = "0.9"
anstyle = "1"
cargo_metadata = { version = "0.23" }
chrono = "0.4"
cipher = "0.5"
clap = { version = "4", features = ["derive"] }
ctr = "0.10"
num-bigint = "0.4"
nx-netloader = { version = "0.1.0", path = "../nx-netloader" }
nx-object = { git = "https://github.com/nx-std/nx-object.git", rev = "f3546be37693de9e0206be13f140dfd84edce3b8", features = ["elf-parsing", "lz4-compression"] }
rand = "0.8"
rsa = "0.9"
schemars = { version = "1", optional = true }
serde = { workspace = true, features = ["std"] }
serde_derive = "1"
serde_json = "1"
sha2 = "0.10"
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["macros", "rt", "signal", "time"] }
toml_edit = "0.22"
tracing.workspace = true
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
xts-mode = "0.6"
zerocopy = "0.8"

[dev-dependencies]
tempfile = "3"
